### ISSUE TITLE
Processing unwanted node_modules

### ISSUE THREAD

**Issue by YPetremann** [robinloeffel/esbuild-plugin-eslint#2]
esbuild-plugin-esling makes eslint process node_modules, which can get annoying if some modules depends on internal eslint linter plugins (like react-dom) or doesn't follow defined codestyle.
ignoring files with eslint makes ignoring messages which are annoyingly hard to remove.

Pull request fixes #1 by adding a glob patterns config to filter files to process before eslint call for each file.

**Comment by talks2much** [comment]
@robinloeffel This plugin is tooo naive and I don't think it yet ready to be on the production. It seems it slows down esbuild output. Also paths are not configurable (what if I want to lint `.vue` or css?). I wonder why didn't you use `.onEnd` callback with paths configurable (or it can track paths even automatically). Anyway, I highly appreciate any thoughts..

**Comment by robinloeffel** [comment]
In https://github.com/robinloeffel/esbuild-plugin-eslint/commit/e05473583ab02dba37d622ad393231f70b500cdf I've fixed a handful of issues, including the one you both are addressing. It now ignores `node_modules` completely, you may define your own `filter` for `esbuild`, which allows you to lint `.vue` files or whatever else you please, and I've moved the work that ESLint does out of the `onLoad` and into the `onEnd` hook. Thanks for you guys' feedback!
