### ISSUE TITLE
Release 0.3.1 will only show errors for one file per repository

### ISSUE THREAD

**Issue by KKoukiou** [robinloeffel/esbuild-plugin-eslint#6]
The problematic line is https://github.com/robinloeffel/esbuild-plugin-eslint/commit/9b25f90c8027c34710d692278a21bd0d54e674bd#diff-88a99604221821c7258fe9c24fc58a4ef42242b97aeae97d6c438db3f62be6cdR23 

Eslint will return an array of results, one result per file. With this change you store in the 'result' variable the first item of the array.
See:
const [result] = [1,2,3,4]
result will be here 1

This is not what you want, as in this case, it will ignore all errors apart from the ones for the first file.

**Comment by robinloeffel** [comment]
hey @KKoukiou! thanks for all the feedback! i've now finally figured out what exactly was necessary and have implemented quite a nice solution. you can see it here: https://github.com/robinloeffel/esbuild-plugin-eslint/commit/5151e23644511205b851c8d5e002c951f3691638

hope this works as expected now!

**Comment by KKoukiou** [comment]
This one is fixed. But in the same release (0.3.1) one more issue was introduced. I reported seperately https://github.com/robinloeffel/esbuild-plugin-eslint/issues/8
